add hugging face sentiment analysis api
djdrng/SmartMelody pull request #8
Opened 2022-07-21 18:23 UTC by khanayan123

add hugging face sentiment analysis api

2022-07-21 18:33 UTC, Wayakuyee commented
What do we need to install to run the code? I installed transformers and tried to run it but now it tells me I need PyTorch, TensorFlow, or Flax so I wanna ask in case there is more to install that just those two.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/42020364/180287886-ff734ffb-eb0e-4d62-ad13-745342f19c95.png">

2022-07-21 18:35 UTC, khanayan123 commented
> What do we need to install to run the code? I installed transformers and tried to run it but now it tells me I need PyTorch, TensorFlow, or Flax so I wanna ask in case there is more to install that just those two.
> 
> <img alt="image" width="1260" src="https://user-images.githubusercontent.com/42020364/180287886-ff734ffb-eb0e-4d62-ad13-745342f19c95.png">

right i will update that

2022-07-21 19:52 UTC, alvii147 requested changes

2022-07-21 19:52 UTC, alvii147 commented on parsing_and_analysis/requirements.txt
> +zope.interface @ file:///opt/concourse/worker/volumes/live/8c2d4bd1-6406-47f0-45ce-890992bafbf6/volume/zope.interface_1625036159007/work
There are way too many dependencies here, I think you may have submitted all the dependencies currently in your system. I doubt we need all of these, a lot of them have nothing to do with our codebase. Can you recheck this? Try using a [virtual environment](https://docs.python.org/3/library/venv.html) for this.

Also, some of these entries are a little weird, for e.g.:

```
boto3 @ file:///opt/conda/conda-bld/boto3_1649078879353/work
```

That doesn't look right. Take a look at this [stack overflow post](https://stackoverflow.com/questions/62885911/pip-freeze-creates-some-weird-path-instead-of-the-package-version).

2022-07-21 19:52 UTC, alvii147 commented on parsing_and_analysis/README.md
> +
We shouldn't be installing like this without specifying a version. The requirements should be installed by doing `pip3 install -r requirements.txt`.

2022-07-21 19:52 UTC, alvii147 commented on parsing_and_analysis/main.py
> +
This looks good, can you add some comments that explain how to use this? Possibly mirroring the comments or docstrings in the rest of the Python modules.

2022-07-21 19:52 UTC, alvii147 commented on parsing_and_analysis/main.py
> +def analyzeText(input):
Might wanna change the variable name from `input` to something else as `input` is a Python special keyword. Maybe `input_text`?

2022-07-25 13:49 UTC, alvii147 commented
This looks good. The only thing I'll say is maybe you can take this file out of the `parsing_and_analysis` directory, and just put it in the `backend/` directory because that's where most of the backend stuff is. I know the backend directory is getting crowded, but we'll tidy things up there soon.

2022-07-26 01:25 UTC, Wayakuyee approved these changes
Removed the unnecessary parts in the README, LGTM!

2022-07-26 01:27 UTC, alvii147 approved these changes

2022-07-26 01:46 UTC, merged